import "reflect-metadata";
import type {Metadata} from "next";
import {Inter} from "next/font/google";

import "bootstrap/dist/css/bootstrap.min.css";

import Bootstrap from "@/components/Bootstrap";
import Naviation from "@/components/Navigation";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Naviation />
        {children}
        <Bootstrap />
        </body>
        </html>
    );
}
