"""Alter Board Question Table

Revision ID: 968a77fc874e
Revises: 31ff5a40fed3
Create Date: 2024-09-03 16:05:08.251712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '968a77fc874e'
down_revision: Union[str, None] = '31ff5a40fed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board_questions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('board_questions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board_questions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('board_questions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
